export enum EndpointNames {
    LOGIN = 'login',
    REGISTRATION = 'registration',
    CHECK_EMAIL = 'check-email',
    CONFIRM_EMAIL = 'confirm-email',
    CHANGE_PASSWORD = 'change-password',
    GET_FEEDBACKS = 'get-feedbacks',
    CREATE_FEEDBACK = 'create-feedback',
    GET_TRAINING_LIST = 'get-training-list',
    GET_USER_TRAINING = 'get-user-training',
    CREATE_TRAINING = 'create-training',
    UPDATE_TRAINING = 'update-training',
    GET_USER = 'get-user',
    UPDATE_USER = 'update-user',
    UPLOAD_UMAGE = 'upload-image',
    GET_TARIFS = 'get-tarifs',
    CREATE_TARIF = 'create-tarif',
}
